version: '3.8'
services:
  jenkins:
    build: ./docker/jenkins/
    privileged: true
    ports:
      - "8082:8080"
    container_name: jenkins
  agent:
    build: ./docker/agent
    privileged: true
    user: root
    container_name: agent
    expose:
      - "22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}